[package]
name = "straw-hat-builds"
version = "0.1.0"
edition = "2021"

[dependencies]
ammonia = "4.0.0"
leptos = { version = "0.6.14", features = ["csr", "nightly"] }
pulldown-cmark = { version = "0.12.0", features = ["html"] }
